django_projects/04_Django_CBV/CBV/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('t01/', include('t01_school.urls')),
    path('t02/', include('t02_form.urls')),
    # path('t03/', include('t03_store.urls')),
    path('t04/', include('t04_restfulApi.urls')),
]

django_projects/04_Django_CBV/t02_form/urls.py
from django.urls import path, include
from t02_form.views import RentalReviewView, ThankYouView

app_name = 't02_form'

urlpatterns = [
    path('rental_review/', RentalReviewView.as_view(), name="rental_review"),
    path('thank_you/', ThankYouView.as_view(), name="thank_you")
]

django_projects/04_Django_CBV/t02_form/forms.py
from django import forms

class ReviewForm(forms.Form):
    first_name = forms.CharField(label="first_name", max_length=20)
    last_name = forms.CharField(label="last_name", max_length=20)
    email = forms.EmailField()
    review = forms.CharField(label="please input your review here", max_length=500)

django_projects/04_Django_CBV/t02_form/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .forms import ReviewForm

# Create your views here.

class RentalReviewView(TemplateView):
    template_name = 't02_form/rental_review.html'
    form_class = ReviewForm



class ThankYouView(TemplateView):
    template_name = 't02_form/thank_you.html'

django_projects/04_Django_CBV/t02_form/templates/t02_form/rental_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>rental review</title>
</head>
<body>

    <h1>this is rental review page</h1>

    <a href="{% url 't02_form:thank_you' %}">go to thank you page</a>

    <form action="" method="post">
        {% csrf_token %}
        {#  view 的 form 传出过来 就是 这个值   #}
        {{ form }}
        {#   这就自动是一个button  #}
        <input type="submit" value="老哥点击提交">
    </form>

</body>
</html>

django_projects/04_Django_CBV/t02_form/templates/t02_form/thank_you.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>thank you</title>
</head>
<body>

<h1>thank you a lot</h1>

</body>
</html>